name: app
description: "Super App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  core:
    git:
      url: "https://github.com/nhatanh100304/core"
      ref: "main"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true